### ISSUE TITLE
Apt key has expired

### ISSUE THREAD

**Issue by lavie** [DataDog/ansible-datadog#103]
```
$ apt-key list
/etc/apt/trusted.gpg
--------------------
...

pub   2048R/C7A7DA52 2011-03-16 [expired: 2018-03-04]
uid                  Datadog Packages <package@datadoghq.com>
```

As a result the `Ensure ubuntu apt-key server is present` Debian step is failing.

**Comment by olivielpeau** [comment]
Hi @lavie! Thanks for reporting this and sorry for the trouble. The expiration of that key was expected, however we didn't expect Ansible to fail importing the key when it expired yesterday (apparently Ansible ignores all expired keys when listing installed keys, so after installing an expired key it fails with `key does not seem to have been added`).

Currently removing all references to that old key...

**Comment by olivielpeau** [comment]
Thanks again for reporting this @lavie, should be fixed in version `2.0.1` of the role

**Comment by bartvanhalder** [comment]
Hi @olivielpeau I just installed v2.0.1 but I’m still getting the same error:
{"changed": false, "id": "C7A7DA52", "msg": "key does not seem to have been added"}

Is there something I can do to work around this, or is there anything I'm probably doing wrong?
